language: objective-c
before_install:
  - brew update
  - brew --env
  - brew config
install:
  - brew tap snmsts/roswell

script:
  - find . \( -name \*.c -o -name \*.h \) -type f|xargs wc -l -c
  - find . \( -name \*.lisp -o -name \*.ros \) -type f|xargs wc -l -c
  - brew install roswell --verbose --HEAD
  - ros version
  - ros -v setup
  - ros list
  - ros -v run -- --version
  - ros install sbcl
  - ros -v run -- --version
  - ros install ccl-bin
  - ros -v run -- --version
  - ros config
  - man -Pcat ros
