language: c

compiler:
  - gcc
  - clang

script:
  - sh bootstrap
  - ./configure
  - make
  - sudo make install
  - ros --version
  - ros setup
  - ros run -- --version
  - ros install sbcl || $(cat ~/.roswell/impls/log/sbcl-1.2.7/make.log && exit -1)
